before_script:
    - apt-get update -qq
    - apt-get install -qq git
    - 'which ssh-agent || ( apt-get install -qq openssh-client )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'


stages:
    - deploy

deploy:
    stage: deploy
    type: deploy
    script:
        - ssh root@redoctopus.studio "cd /home/vlad/projects/lms  && git pull origin backend && cd LMS.API && dotnet restore && systemctl stop LMS.service && sudo dotnet publish --configuration Release --output '/home/vlad/publish/lms' && systemctl start LMS.service && exit"
    environment:
        name: redocto
        url: http://redoctopus.studio

